spring:
  application:
    name: kstream-product-merge-example

  kafka:
    bootstrap-servers: localhost:29092
    streams:
      state-dir: ./target/kstream-statestore
      properties:
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    org.springframework.kafka: DEBUG
